"use client";

import { useRef, useEffect, useState } from "react";
import { motion } from "framer-motion";

export function HowItWorks() {
  const steps = [
    {
      number: "01",
      title: "Create Your InsightCast Account",
      description:
        "Join the decentralized forecasting ecosystem in seconds. No central authority, just transparent, permissionless prediction markets.",
    },
    {
      number: "02",
      title: "Choose or Create a Market",
      description:
        "Browse markets generated by the community or propose your own. Multi-outcome forecasting supported.",
    },
    {
      number: "03",
      title: "Add Liquidity or Start Trading",
      description:
        "Provide liquidity or trade outcome shares directly. Fair pricing ensured by AMM bonding curves.",
    },
    {
      number: "04",
      title: "Forecast With Confidence",
      description:
        "Buy and sell outcome shares representing probabilities. Collective intelligence updates market odds in real-time.",
    },
    {
      number: "05",
      title: "Oracle Resolution & Rewards",
      description:
        "Switchboard oracles verify outcomes. Community governance resolves disputes. Winners get automatic payouts.",
    },
    {
      number: "06",
      title: "Grow Your Reputation",
      description:
        "Accurate forecasters earn reputation points, badges, higher market limits, and governance influence.",
    },
  ];

  const containerRef = useRef<HTMLDivElement>(null);
  const [scrollX, setScrollX] = useState(0);

  // Auto-scroll effect
  useEffect(() => {
    const stepWidth = 320; // card width + gap (adjust based on Tailwind widths)
    let scrollPos = 0;

    const interval = setInterval(() => {
      if (!containerRef.current) return;
      scrollPos += 1; // pixels per tick
      if (scrollPos >= containerRef.current.scrollWidth / 2) {
        scrollPos = 0; // loop scroll
      }
      containerRef.current.scrollLeft = scrollPos;
    }, 16); // ~60fps

    return () => clearInterval(interval);
  }, []);

  return (
    <section id="how-it-works" className="container mx-auto px-4 py-20">
      <div className="text-center mb-16 animate-on-scroll">
        <h2 className="text-3xl md:text-4xl font-bold mb-4">
          How InsightCast Works
        </h2>
        <p className="mx-auto max-w-2xl text-slate-600 dark:text-slate-300">
          A decentralized forecasting marketplace powered by AMMs, oracles, and
          community governance.
        </p>
      </div>

      <div
        ref={containerRef}
        className="flex gap-6 overflow-hidden py-4"
        style={{ scrollbarWidth: "none" }}
      >
        {/* duplicate steps for seamless looping */}
        {[...steps, ...steps].map((step, i) => (
          <motion.div
            key={i}
            whileHover={{ scale: 1.05, rotateZ: 1 }}
            className="relative flex-shrink-0 w-72 md:w-80 lg:w-96 rounded-2xl border bg-white dark:bg-slate-900 p-6 shadow-lg cursor-pointer transition-all duration-300"
          >
            <div className="absolute -top-4 -left-4 flex h-10 w-10 items-center justify-center rounded-full bg-gradient-to-r from-emerald-500 to-blue-500 text-sm font-bold text-white">
              {step.number}
            </div>
            <h3 className="mb-2 text-xl font-semibold text-slate-900 dark:text-white">
              {step.title}
            </h3>
            <p className="text-slate-600 dark:text-slate-300">{step.description}</p>
            <div className="absolute -bottom-6 -right-6 h-16 w-16 rounded-full bg-gradient-to-br from-emerald-500/20 to-blue-500/20 blur-3xl animate-float-slow"></div>
          </motion.div>
        ))}
      </div>
    </section>
  );
}
